func ship() -> Dialogue:
	var dlg := Dialogue.new()
	dlg.speaker("Babble")
	dlg.say("Is she still doing well? No engine trour-ourble?")
	dlg.say("Say, Jay, when are you ever going to get her repainted?")
	dlg.say("Her color's awfully faded. I know a few people, you know.")
	dlg.say("Hey! What are you glaring at me for?")
	return dlg


func glass() -> Dialogue:
	var dlg := Dialogue.new()
	dlg.speaker("Babble")
	dlg.say("Oh, wow...")
	dlg.say("I've always thought it had a strange beauty to it, didn't you?")
	dlg.say("Don't you get that feeling in your throat flying through it now?")
	dlg.say("Maybe that's just the glass, oahaha!")
	dlg.say("It still feels off-limits to me! Any second I'll hit the \"no trespassing\" sign, oaha!")
	dlg.say("And the guards, and the... glint of the sun.")
	dlg.say("Well, the foundations sank, but the glass still hangs around up here.")
	dlg.say("Rumor has it, reveberating between the crushed glass...")
	dlg.say("You can still hear the dying screams of its occupants...!")
	dlg.say("Eahaha! But that's just rumor.")
	dlg.say("It was empty when it all came down.")
	dlg.say("Except for the gaping hole, oeheheh! What a stroke of luck!")
	dlg.speaker("Agomi")
	dlg.say("Jay.")
	dlg.speaker("Babble")
	dlg.say("...")
	dlg.say("Hey, listen, Jay... did it ever drift by, when you were small?")
	dlg.say("I remember I used to, er...")
	dlg.say("When everyone was afraid of getting sliced up?")
	dlg.say("Something about it would glue me to the window.")
	dlg.say("It was so pretty, don't you think? In a way.")
	dlg.say("Glinting gently in the sun.")
	dlg.speaker("Agomi")
	dlg.say("Jay.")
	dlg.speaker("Babble")
	dlg.say("Jay, do you think...")
	dlg.speaker("Agomi")
	dlg.say("Jay, get back to work.")
	dlg.say("You're getting your ear talked off.")
	dlg.push(Game.data.set.bind("babble_friendship", Game.data.get("babble_friendship", 0) + 1))
	return dlg
